# Generated by Django 4.2.7 on 2024-09-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 17, 19, 22, 448388, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
