# Generated by Django 4.2.7 on 2024-09-29 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedition',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Поход', 'verbose_name_plural': 'Походы'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
        migrations.AddField(
            model_name='expedition',
            name='viking',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='square',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 12, 40, 36, 4486, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='placeexpedition',
            name='expedition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.expedition'),
        ),
        migrations.AlterField(
            model_name='placeexpedition',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.place'),
        ),
        migrations.AlterModelTable(
            name='placeexpedition',
            table='place_expedition',
        ),
    ]
