# Generated by Django 4.2.7 on 2024-09-29 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expedition_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 21, 40, 46, 3693, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
