# Generated by Django 4.2.7 on 2024-09-30 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expedition_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 1, 52, 56, 996164, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
