# Generated by Django 4.2.7 on 2024-10-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcalculation',
            unique_together={('product', 'calculation')},
        ),
    ]
