# Generated by Django 4.2.7 on 2024-10-01 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expedition_place_placeexpedition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 21, 48, 7, 258993, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
