# Generated by Django 4.2.7 on 2024-10-24 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_expedition_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 2, 47, 20, 129754, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
