# Generated by Django 4.2.7 on 2024-10-07 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expedition_place_placeexpedition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeexpedition',
            options={'ordering': ('value',), 'verbose_name': 'м-м', 'verbose_name_plural': 'м-м'},
        ),
        migrations.AlterField(
            model_name='expedition',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 22, 43, 26, 649842, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
